apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-world-ns1
  namespace: argocd
spec:
  description: "Project for hello-world app in ns1"
  sourceRepos:
    - "*"
  destinations:
    - namespace: app-ns1
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

